[2025-05-12T21:05:17.550+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-12T21:05:17.565+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_daily_pipeline.dbt_run manual__2025-05-12T20:00:10.933027+00:00 [queued]>
[2025-05-12T21:05:17.568+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_daily_pipeline.dbt_run manual__2025-05-12T20:00:10.933027+00:00 [queued]>
[2025-05-12T21:05:17.568+0100] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-05-12T21:05:17.572+0100] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-05-12 20:00:10.933027+00:00
[2025-05-12T21:05:17.578+0100] {logging_mixin.py:188} WARNING - /Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=4291) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-12T21:05:17.578+0100] {standard_task_runner.py:64} INFO - Started process 4293 to run task
[2025-05-12T21:05:17.577+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_daily_pipeline', 'dbt_run', 'manual__2025-05-12T20:00:10.933027+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/var/folders/x8/bvc5rcpd5t12mfz1khbckdsm0000gn/T/tmp2_g306pd']
[2025-05-12T21:05:17.579+0100] {standard_task_runner.py:91} INFO - Job 25: Subtask dbt_run
[2025-05-12T21:05:17.596+0100] {task_command.py:426} INFO - Running <TaskInstance: youtube_daily_pipeline.dbt_run manual__2025-05-12T20:00:10.933027+00:00 [running]> on host macbookair.lan
[2025-05-12T21:05:17.738+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='youtube_daily_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T20:00:10.933027+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-12T20:00:10.933027+00:00'
[2025-05-12T21:05:17.739+0100] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-12T21:05:17.746+0100] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/x8/bvc5rcpd5t12mfz1khbckdsm0000gn/T
[2025-05-12T21:05:17.746+0100] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd "/Users/moeinfahmide/Desktop/Job/Learning/Data Engineering/projects/youtube/youtube_dbt" && dbt run --profiles-dir "/Users/moeinfahmide/Desktop/Job/Learning/Data Engineering/projects/youtube" --models staging+ marts+']
[2025-05-12T21:05:17.750+0100] {subprocess.py:86} INFO - Output:
[2025-05-12T21:05:18.717+0100] {subprocess.py:93} INFO - [0m20:05:18  Running with dbt=1.9.4
[2025-05-12T21:05:18.719+0100] {subprocess.py:93} INFO - [0m20:05:18  Encountered an error:
[2025-05-12T21:05:18.719+0100] {subprocess.py:93} INFO - Runtime Error
[2025-05-12T21:05:18.719+0100] {subprocess.py:93} INFO -   Could not find profile named 'youtube_dbt'
[2025-05-12T21:05:19.213+0100] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-12T21:05:19.214+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-12T21:05:19.218+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-12T21:05:19.220+0100] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=youtube_daily_pipeline, task_id=dbt_run, run_id=manual__2025-05-12T20:00:10.933027+00:00, execution_date=20250512T200010, start_date=20250512T200517, end_date=20250512T200519
[2025-05-12T21:05:19.224+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 4293)
[2025-05-12T21:05:19.233+0100] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-05-12T21:05:19.241+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-12T21:05:19.243+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
