[2025-05-12T20:59:55.615+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-12T20:59:55.631+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_daily_pipeline.dbt_run manual__2025-05-12T19:59:51.596061+00:00 [queued]>
[2025-05-12T20:59:55.634+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_daily_pipeline.dbt_run manual__2025-05-12T19:59:51.596061+00:00 [queued]>
[2025-05-12T20:59:55.634+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-05-12T20:59:55.639+0100] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-05-12 19:59:51.596061+00:00
[2025-05-12T20:59:55.645+0100] {logging_mixin.py:188} WARNING - /Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=4059) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-12T20:59:55.645+0100] {standard_task_runner.py:64} INFO - Started process 4063 to run task
[2025-05-12T20:59:55.644+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_daily_pipeline', 'dbt_run', 'manual__2025-05-12T19:59:51.596061+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/var/folders/x8/bvc5rcpd5t12mfz1khbckdsm0000gn/T/tmpiuv_lw85']
[2025-05-12T20:59:55.646+0100] {standard_task_runner.py:91} INFO - Job 21: Subtask dbt_run
[2025-05-12T20:59:55.664+0100] {task_command.py:426} INFO - Running <TaskInstance: youtube_daily_pipeline.dbt_run manual__2025-05-12T19:59:51.596061+00:00 [running]> on host macbookair.lan
[2025-05-12T20:59:55.808+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='youtube_daily_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T19:59:51.596061+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-12T19:59:51.596061+00:00'
[2025-05-12T20:59:55.808+0100] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-12T20:59:55.816+0100] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/x8/bvc5rcpd5t12mfz1khbckdsm0000gn/T
[2025-05-12T20:59:55.816+0100] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd "/Users/moeinfahmide/Desktop/Job/Learning/Data Engineering/projects/youtube/youtube_dbt" && dbt run --profiles-dir "/Users/moeinfahmide/Desktop/Job/Learning/Data Engineering/projects/youtube" --models staging+ marts+']
[2025-05-12T20:59:55.821+0100] {subprocess.py:86} INFO - Output:
[2025-05-12T20:59:57.211+0100] {subprocess.py:93} INFO - [0m19:59:57  Running with dbt=1.9.4
[2025-05-12T20:59:57.214+0100] {subprocess.py:93} INFO - [0m19:59:57  Encountered an error:
[2025-05-12T20:59:57.214+0100] {subprocess.py:93} INFO - Runtime Error
[2025-05-12T20:59:57.214+0100] {subprocess.py:93} INFO -   Could not find profile named 'youtube_dbt'
[2025-05-12T20:59:57.758+0100] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-12T20:59:57.759+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-12T20:59:57.764+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-12T20:59:57.767+0100] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_daily_pipeline, task_id=dbt_run, run_id=manual__2025-05-12T19:59:51.596061+00:00, execution_date=20250512T195951, start_date=20250512T195955, end_date=20250512T195957
[2025-05-12T20:59:57.771+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 4063)
[2025-05-12T20:59:57.791+0100] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-05-12T20:59:57.800+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-12T20:59:57.800+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
